library(ggplot2)
library(dplyr)

# Parameters
r <- 1  # Radius of the rolling circle
phi_full <- seq(0, 4 * pi, length.out = 500)  # Full range of rotation angles (phi)

# Generate the complete cycloid curve
df_cicloide <- data.frame(
  x = r * (phi_full - sin(phi_full)),     # x(t) = r*(φ - sin(φ))
  y = r * (1 - cos(phi_full))             # y(t) = r*(1 - cos(φ))
)

# Select specific rotation angles to illustrate different "frames" in time
phi_frames <- seq(0, 4 * pi, length.out = 7)  # 7 time moments (frames)

# Create data for the rolling circles and the generating point at each frame
circle_list <- list()
points_list <- list()

for (i in seq_along(phi_frames)) {
  phi_i <- phi_frames[i]       # Current rotation angle
  cx <- r * phi_i              # Center x-position of the circle
  cy <- r                      # Center y-position is always the radius (rolling on x-axis)
  theta <- seq(0, 2 * pi, length.out = 100)  # Angle values to draw the circle
  
  # Data for the circle's perimeter at this frame
  circle_df <- data.frame(
    x = cx + r * cos(theta),   # Circle's x-coordinates
    y = cy + r * sin(theta),   # Circle's y-coordinates
    group = i                  # Group for faceting or color (optional)
  )
  circle_list[[i]] <- circle_df
  
  # Generating point (point on the rim tracing the cycloid)
  pg_x <- cx - r * sin(phi_i)  # Horizontal position of the tracing point
  pg_y <- cy - r * cos(phi_i)  # Vertical position of the tracing point
  points_list[[i]] <- data.frame(x = pg_x, y = pg_y)
}

# Combine all the circles and generating points into data frames
df_circles <- bind_rows(circle_list)
df_points <- bind_rows(points_list)

# Plot using ggplot2
ggplot() +
  # Plot the cycloid path
  geom_path(data = df_cicloide, aes(x, y), color = "blue", size = 1.2) +
  
  # Plot all the rolling circles (dashed)
  geom_path(data = df_circles, aes(x, y, group = group), color = "black", linetype = "dashed") +
  
  # Plot the generating points at each frame
  geom_point(data = df_points, aes(x, y), color = "red", size = 2.5) +
  
  coord_fixed() +  # Keep aspect ratio 1:1 so circles appear circular
  theme_minimal() +
  labs(title = "Cycloid generated by a rolling wheel at different times") +
  theme(axis.title = element_blank())  # Remove axis titles

# Export the plot to a PNG file
ggsave("cycloid.png", width = 8, height = 4, dpi = 300)

